### ISSUE TITLE
Beets integration

### ISSUE THREAD

**Issue by ztomer** [Migz93/lidarr-download-automation#29]
I believe that adding [beets ](https://beets.io/) as a post-processing option can be beneficial for the script users. 
What do you think?

**Comment by Migz93** [comment]
"External" post processing option was added with Beets mentioned as a tool that could utilise this. Pull request #8 specifically.

I don't use Beets myself, is there any kind of watch folder function? As then you can have the files moved to a specific folder to be post processed by beets?

**Comment by ztomer** [comment]
As far as I'm aware beets does not have a monitoring mode (only on-demand, one time execution).
An order of operations that can allow all the entries to be processed will probably be something like:

1. Download an Album to folder X
2. Run Beets on folder X 
3. Invoke Lidarr on folder X
4. Go to 1 :)

**Comment by Migz93** [comment]
Having a look I'm struggling to find an API that allows to specify import.
I've found [this ](https://beets.readthedocs.io/en/v1.4.4/plugins/web.html) and [this](https://beets.readthedocs.io/en/v1.3.17/dev/api.html). Neither of which have what we'd need.

We'll have to have a more thorough look

**Comment by RandomNinjaAtk** [comment]
1, 2 and 4 are possible, just not 3. After it gets fed into beets, there is no way to account for how it will be processed to send it back to lidarr. There is too many variables to account for and it would only work if a user used it in the exact same way as everyone else (same beets config file and installation setup). Your better off customizing the script to enable the functionality your looking for since it is completely possible, just can't be easily added to the script for because of too many possible variations/variables.
